import "./globals.css";

export const metadata = {
  title: "Lēmums",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`} style={{ paddingTop: "30vh" }}>
        {children}
      </body>
    </html>
  );
}
